apiVersion: v1
kind: Service
metadata:
  name: svcat-etcd-client-service-lb
  namespace: openshift-operators
spec:
  ports:
  - name: client
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    etcd_cluster: svcat-etcd-cluster
  type: LoadBalancer
